/**
 * Product image delivery.
 *
 * Resolution order for every catalog image:
 *   1. The Cloudinary public ID recorded in `src/data/cloudinary-manifest.json`
 *      (generated by `scripts/upload-products-to-cloudinary.mjs`).
 *   2. The original root-relative local path under `public/assets/products/`.
 *
 * The manifest holds safe metadata only — relative source path, public ID,
 * secure URL, dimensions, and format. No credential is involved: Cloudinary
 * delivery URLs are public by design and need only the cloud name.
 *
 * Keeping the local path as a fallback means the storefront still renders if
 * the manifest is missing or an image was never uploaded.
 */
import manifest from '@/data/cloudinary-manifest.json'
import { buildCloudinaryUrl, isCloudinaryConfigured } from '@/lib/cloudinary'

/** Map of `/assets/products/...` → manifest entry. */
const IMAGES = manifest?.images ?? {}

/** True when at least one image resolves through Cloudinary. */
export const isCloudinaryDeliveryActive =
  isCloudinaryConfigured && Object.keys(IMAGES).length > 0

/** The manifest entry for a local path, or `undefined`. */
export function getManifestEntry(localSrc) {
  return localSrc ? IMAGES[localSrc] : undefined
}

/**
 * Catalog image transforms.
 *
 * `c_pad` keeps the whole product inside the frame — a racket or a cricket bat
 * must not be cropped to fit an apparel-shaped tile — and pads with white to
 * match the light shopping surfaces. Quality and format are chosen by
 * Cloudinary (`q_auto`, `f_auto`), which the URL builder already applies.
 */
const CATALOG_TRANSFORM = { crop: 'pad', background: 'white' }

/** Widths offered to the browser for responsive catalog imagery. */
const CATALOG_WIDTHS = [240, 360, 480, 720, 960]

/**
 * Resolve one catalog image to its delivery URL.
 * Falls back to the local path when the image is not in the manifest.
 */
export function resolveProductImage(localSrc, options = {}) {
  const entry = getManifestEntry(localSrc)
  if (!entry) return localSrc

  const url = buildCloudinaryUrl(entry.publicId, { ...CATALOG_TRANSFORM, ...options })
  return url ?? localSrc
}

/**
 * Build a `srcset` for a catalog image, or `null` when only the local file is
 * available (a single local JPEG has no alternate widths to offer).
 */
export function buildProductSrcSet(localSrc, widths = CATALOG_WIDTHS) {
  const entry = getManifestEntry(localSrc)
  if (!entry) return null

  return widths
    .map((width) => {
      const url = buildCloudinaryUrl(entry.publicId, { ...CATALOG_TRANSFORM, width })
      return url ? `${url} ${width}w` : null
    })
    .filter(Boolean)
    .join(', ')
}

/** How many catalog images are served from Cloudinary. Used by diagnostics. */
export function getDeliveryStats() {
  return {
    manifestCount: Object.keys(IMAGES).length,
    cloudinaryConfigured: isCloudinaryConfigured,
    active: isCloudinaryDeliveryActive,
  }
}
